version: '3.7'
services:
  dynamodb:
    image:  amazon/dynamodb-local
    container_name: my-dynamodb
    hostname: dynamodb
    restart: unless-stopped
    volumes:
      -  ./my-dynamodb-data:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"

#   serverless:
#     platform: linux/arm64
#     links: 
#       - dynamodb
#     depends_on:
#       - dynamodb
#     build: .
#     ports:
#       - 3000:3000
#     volumes:
#       - .:/usr/app

# volumes:
#   dynamodb-data:
#     driver: local